FROM golang:1.16.3 AS go
COPY ./backend /app
WORKDIR /app
#RUN migrate -database  '$DB_DRIVER_NAME://$DB_USERNAME:$DB_USER_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_NAME' -path db/migrations up
RUN go build
FROM debian:bullseye-slim
RUN apt update \
    && mkdir /app
COPY --from=go /app/yajirobe /app/yajirobe
WORKDIR /app
CMD ["./yajirobe"]
