FROM golang:1.16.3-alpine AS go
COPY ./backend /app
WORKDIR /app
#RUN migrate -database  '$DB_DRIVER_NAME://$DB_USERNAME:$DB_USER_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_NAME' -path db/migrations up
RUN go build
FROM alpine:3.14.2
RUN apk update \
    && mkdir /app
COPY --from=go /app/yajirobe /app/yajirobe
WORKDIR /app
CMD ["./yajirobe"]