version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.api
    tty: true
    volumes:
      - .:/app
    stdin_open: true
    depends_on:
      - mysql
    ports:
      - 50523:50523
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile.front
    tty: true
    volumes:
      - .:/app
    ports:
      - 56294:56294
  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - 58524:58524
    volumes:
      - ./backend/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/mysql_data:/var/lib/mysql
    env_file: .env.dev.db