CREATE TABLE IF NOT EXISTS users(
    id VARCHAR(20) PRIMARY KEY,
    pw VARCHAR(512) NOT NULL,
    private_key VARCHAR(2048) NOT NULL,
    public_key VARCHAR(2048) NOT NULL
);
CREATE TABLE IF NOT EXISTS incomes(
    id SERIAL PRIMARY KEY,
    dt DATETIME NOT NULL,
    summary VARCHAR(200) NOT NULL,
    income INT NOT NULL,
    tag VARCHAR(200) NOT NULL,
    user VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS categories(
    category_code VARCHAR(20) PRIMARY KEY,
    category_name VARCHAR(20) NOT NULL
);