name: CI/CD
on:
  push:
    branches:
      - master
env:
  API_IMAGE: ghcr.io/naoki-urabe/yajirobe/api:prod
  FRONT_IMAGE: ghcr.io/naoki-urabe/yajirobe/front:prod
  TASK_IMAGE: ghcr.io/naoki-urabe/yajirobe/task:prod
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Add environment variable to .env.prod
        run: |
          echo MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env.prod.db
          echo MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}" >> .env.prod.db
          echo MYSQL_TCP_PORT="${{ secrets.DB_PORT}}" >> .env.prod.db
      - name: Add environment variable to .env.prod.api
        run: |
          echo API_PORT="${{ secrets.API_PORT}}" >> .env.prod.api
          echo DB_DRIVER_NAME=mysql >> .env.prod.api
          echo DB_NAME="${{ secrets.MYSQL_DATABASE }}" >> .env.prod.api
          echo DB_USERNAME=root >> .env.prod.api
          echo DB_USER_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env.prod.api
          echo DB_HOST=mysql_prod >> .env.prod.api
          echo DB_PORT="${{ secrets.DB_PORT }}" >> .env.prod.api
      - name: Add environment variable to .env.prod.front
        run: |
          echo VUE_APP_HOST="${{ secrets.API_HOST }}" >> front/.env.production
          echo VUE_APP_API_PORT="${{ secrets.API_PORT }}" >> front/.env.production
          echo VUE_APP_FRONT_PORT="${{ secrets.FRONT_PORT }}" >> front/.env.production
      - name: Add environment variable to .env.prod.front
        run: |
          echo VUE_APP_HOST="${{ secrets.API_HOST }}" >> .env.prod.front
          echo VUE_APP_API_PORT="${{ secrets.API_PORT }}" >> .env.prod.front
          echo VUE_APP_FRONT_PORT="${{ secrets.FRONT_PORT }}" >> .env.prod.front
      - name: Set .env
        run: |
          echo API_PORT="${{ secrets.API_PORT }}" >> .env
          echo VUE_APP_FRONT_PORT="${{ secrets.FRONT_PORT }}" >> .env
          echo DB_PORT="${{ secrets.DB_PORT}}" >> .env
      - name: Log in to Github packages
        run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker-compose -f docker-compose.ci.yml build
      - name: push image
        run: |
          docker push ${{ env.API_IMAGE }}
          docker push ${{ env.FRONT_IMAGE }}
          docker push ${{ env.TASK_IMAGE }}
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: deploy
        run: bash scripts/deploy.sh
        env:
          HOST: ${{ secrets.HOST_NAME }}
          USER: ${{ secrets.USER }}
          HOST_PORT: ${{ secrets.HOST_PORT }} 
